// Users Actions
export const SET_AVATAR = 'SET_AVATAR'
export const SET_USER = 'SET_USER'
export const SET_TOKEN = 'SET_TOKEN'

// POST ACTIONS
export const SET_MONDAY = 'SET_MONDAY'
export const SET_FRIDAY = 'SET_FRIDAY'
export const SET_HIT_PARADE = 'SET_HIT_PARADE'

// TEMPLATE ACTIONS
export const SET_TITLE = "SET_TITLE"

// Deprecated
export const FETCHING_USER_REQUEST = 'FETCHING_USER_REQUEST'
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS'
export const FETCHING_USER_ERROR = 'FETCHING_USER_ERROR'
