export const SET_AVATAR = 'SET_AVATAR'
export const SET_USER = 'SET_USER'
export const SET_TOKEN = 'SET_TOKEN'


// Deprecated
export const FETCHING_USER_REQUEST = 'FETCHING_USER_REQUEST'
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS'
export const FETCHING_USER_ERROR = 'FETCHING_USER_ERROR'
